openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /api/v1/pricing/calculate:
    post:
      summary: Calculate pricing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                zone:
                  type: string
                organization_id:
                  type: string
                item_type:
                  type: string
                total_distance:
                  type: number
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { total_price: 20.5 }
